version: "3.5"
services:
  db:
    image: pgvector/pgvector:pg15
    restart: always
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5420:5432"
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - "6378:6379"
