-- Custom SQL migration file, put your code below! --
INSERT INTO topics (name, icon) VALUES
    ('Marketing', 'Megaphone'),
    ('Finanças', 'BadgeDollarSign'),
    ('Negócios', 'BriefcaseBusiness'),
    ('Desenvolvimento Pessoal', 'UserPlus'),
    ('Vendas', 'ShoppingCart'),
    ('Saúde', 'Heart'),
    ('Relacionamentos', 'Users'),
    ('Idiomas', 'Globe'),
    ('Carreira', 'Briefcase'),
    ('Espiritualidade', 'Sparkles'),
    ('Moda', 'Award'),
    ('Advocacia', 'Gavel'),
    ('Design', 'PenTool'),
    ('Programação', 'Code'),
    ('Vendas', 'ShoppingBag'),
    ('Redes sociais', 'Share2'),
    ('Arte', 'Palette'),
    ('Esportes', 'Trophy');
