name: Deploy to Trigger.dev (stg)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # docker setup - part 1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      # docker setup - part 2
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: container-registry.br-se1.magalu.cloud
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: 🚀 Deploy Trigger.dev
        env:
          TRIGGER_SECRET_KEY: ${{ secrets.TRIGGER_ACCESS_TOKEN }}
          TRIGGER_ACCESS_TOKEN: ${{ secrets.TRIGGER_ACCESS_TOKEN }}
          TRIGGER_API_URL: https://trigger.dev.albieri.ai
        run: |
          npx trigger.dev@3.3.17 deploy --self-hosted --push --namespace scarf --load-image
